baseURL = 'https://ddnio.github.io/'
languageCode = 'en-us'
title = 'ddnio的胡思乱想'
theme = "paper"
# markup.goldmark.renderer.unsafe = true

[params]
  # home page profile
  avatar = 'https://ddnio-blog.oss-cn-shenzhen.aliyuncs.com/uPic/20240627out-2%20(1)_%E5%89%AF%E6%9C%AC.png'                 # gravatar email or image url
  name = 'Nio'
  bio = 'say some thing'

#     twitter = 'ddnioo'
    github = 'ddnio'

# Giscus 评论系统配置
[params.giscus]
  repo = "ddnio/ddnio.github.io"
  repoId = "R_kgDOMM_LVw"
  category = "Announcements"
  categoryId = "DIC_kwDOMM_LV84CxYyR"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "zh-CN"
